// export interface BTTVEmotes {

// }

export interface BTTVEmotes<T> {
  AAUGH: T
  AngelThump: T
  BALDSPIN: T
  BANERS: T
  BAOMN: T
  BBoomer: T
  BIGRACC: T
  BLAAP: T
  BLAPBLAP: T
  BOOBAP: T
  BaldiPls: T
  Bedge: T
  Borpa: T
  BorpaU: T
  BroBalt: T
  BroPls: T
  CHECKERS: T
  CLICK: T
  COCKA: T
  COCKING: T
  CODE1: T
  CRAWLERS: T
  SHITTERS: T
  SHRUGGERS: T
  SHUSHERS: T
  SNEAKERS: T
  SOLARFLARE: T
  SPEEDERS: T
  Sadge: T
  SaltyCorn: T
  ShoopDaWhoop: T
  SoulShroom: T
  SourPls: T
  SqShy: T
  Sussy: T
  TANTIES: T
  TWERKERS: T
  TaxiBro: T
  TeaTime: T
  TeaTime2: T
  TriKool: T
  Tssk: T
  TwaT: T
  VANiSH: T
  VIBERS: T
  VapeNation: T
  VeryPog: T
  VisLaud: T
  WAYTOODANK: T
  WEIRD: T
  WICKED: T
  WOWERS: T
  WatChuSay: T
  WeeWoo: T
  WifeCheck: T
  Wokege: T
  Wowee: T
  WubTF: T
  YAPPP: T
  Yoda1: T
  ariW: T
  ayayaJAM: T
  bUrself: T
  baldDab: T
  baldFlick: T
  baldFloss: T
  baldYAPPP: T
  baldYIKES: T
  billyReady: T
  borpaD: T
  borpaSpin: T
  bttvNice: T
  catJAM: T
  coomTime: T
  cvHazmat: T
  cvL: T
  cvMask: T
  cvR: T
  docCBT: T
  doctorPls: T
  eddieBaldManSmash: T
  eddieKnead: T
  eddieSpin: T
  fuBaldi: T
  gachiBASS: T
  gachiROLL: T
  gachiSAIYAN: T
  gachiW: T
  haHAA: T
  jesusBeBallin: T
  lennyBASS: T
  lennyWalk: T
  lulWut: T
  marioRun: T
  mmHmm: T
  modCheck: T
  monakS: T
  monkaGIGA: T
  monkaS: T
  moon2BASS: T
  moon2SCOOTS: T
  notsquishY: T
  nutTasty: T
  nymnCorn: T
  peepersD: T
  peepoBOOM: T
  peepoCheering: T
  peepoD: T
  peepoFAT: T
  peepoFlute: T
  peepoGiggles: T
  peepoGolfClap: T
  peepoNaruSprint: T
  peepoPothole: T
  peepoRIPLeave: T
  peepoShy: T
  peepoSteer: T
  peepoStroke: T
  peepoT: T
  peepoWTF: T
  peepoWine: T
  peepoWink: T
  pepeJAM: T
  pepeMetal: T
  pepeP: T
  pepePHONE: T
  pepePHONER: T
  pepeSmoke: T
  pepeW: T
  ppHop: T
  qynoaLurks: T
  robDab: T
  robPls: T
  sosGame: T
  takeTheRob: T
  tehPoleCat: T
  tinyTEETH: T
  ':tf:': T
  CUMDETECTED: T
  CandianRage: T
  ChugU: T
  CiGrip: T
  Clap: T
  Clap2: T
  ConcernDoge: T
  Copege: T
  Corpa: T
  CowJAM: T
  CruW: T
  CumCoke: T
  'D:': T
  DDoomer: T
  DESKCHAN: T
  DOCING: T
  DOUBTERS: T
  DatSauce: T
  Deadlole: T
  Dingdingdingding: T
  DogChamp: T
  DonoWall: T
  DrumTime: T
  DuckerZ: T
  EASY: T
  EATO: T
  EEKUM: T
  FCreep: T
  FLAPPERS: T
  FeelsAmazingMan: T
  FeelsAyayaMan: T
  FeelsBadMan: T
  FeelsBirthdayMan: T
  FeelsGoodMan: T
  FeelsGoogMan: T
  FeelsLateMan: T
  FeelsSnowyMan: T
  FeelsStrongMan: T
  FeelsWowMan: T
  FireSpeed: T
  FishMoley: T
  ForeverAlone: T
  GAMBA: T
  GAWKGAWK: T
  GECKW: T
  GabeN: T
  Grumpge: T
  GuitarTime: T
  HACKERMANS: T
  HARD: T
  HUMPERS: T
  HYPERCLAP: T
  HYPERCLAP2: T
  HYPERLULWUT: T
  HYPERNODDERS: T
  HYPERNOPERS: T
  HYPERRACC: T
  HYPERROBDAB: T
  HYPERpeepoD: T
  HailHelix: T
  Hhhehehe: T
  IHATEYOU: T
  JOHNSOULS: T
  KKomrade: T
  KKona: T
  KKool: T
  KaRappa: T
  Kachorpa: T
  KappaCool: T
  Kissabrother: T
  Kissahomie: T
  Kissapregomie: T
  KomodoChomp: T
  LGiggle: T
  Libido: T
  LuL: T
  'M&Mjc': T
  MAHALO: T
  MLADY: T
  MYAAA: T
  Madge: T
  NODDERS: T
  NOMMERS: T
  NOPERS: T
  NOTED: T
  NaM: T
  NaMPls: T
  NotSure: T
  OMEGALAUGHING: T
  OMEGAPOGGERS: T
  Okayge: T
  PEEPEES: T
  PEEPERS: T
  PEPELEPSY: T
  PEPW: T
  PETTHEBALDIE: T
  PETTHEEDDIE: T
  PETTHEQYNOA: T
  POGGERS: T
  POGPLANT: T
  POOTERS: T
  PUKERS: T
  PeepeegaChat: T
  PepeHands: T
  PepePls: T
  PepeSpin: T
  PianoTime: T
  Poggers: T
  PoleDoge: T
  Prayge: T
  REFRACTING: T
  Rainge: T
  RapThis: T
  RareMoon: T
  RarePepe: T
  RonSmug: T
}

export interface ChatInstanceConfig {
  channels: string[]
  maximumEmoteLimit?: number
  maximumEmoteLimit_pleb?: number
  duplicateEmoteLimit?: number
  duplicateEmoteLimit_pleb?: number
  gifAPI?: string
}

interface ChatInstanceListeners {
  emotes: Function[]
}

export interface ChatInstance {
  bttvEmotes: BTTVEmotes<string>
  config: ChatInstanceConfig
  emoteGifs: any
  emotes: any
  listeners: ChatInstanceListeners
}

export interface QueryVars {
  channels: object
}
